<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A97EKAP" ignored="0" name="FailTest" tests="1" failures="1" timestamp="19 May 2020 09:25:51 GMT" time="51.125" errors="0">
  <testcase name="failvalidateTitle" time="0.58" classname="Academy.FailCase">
    <failure type="java.lang.AssertionError" message="expected [Feature fail title] but found [FEATURED COURSES]">
      <![CDATA[java.lang.AssertionError: expected [Feature fail title] but found [FEATURED COURSES]
at Academy.FailCase.failvalidateTitle(FailCase.java:31)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failvalidateTitle -->
</testsuite> <!-- FailTest -->
